export const images = [
    "https://4kwallpapers.com/images/walls/thumbs_2t/26751.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/26739.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/26273.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/26085.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/25965.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/26049.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/24830.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/22251.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/14717.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/17363.jpeg",
    "https://image.tmdb.org/t/p/w1920/i4PpW1XyRlBuSNSIBRIIwSjEpjl.jpg",
    "https://image.tmdb.org/t/p/w1920/lkDYN0whyE82mcM20rwtwjbniKF.jpg",
    "https://image.tmdb.org/t/p/w1920/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg",
    "https://image.tmdb.org/t/p/w1920/flxau5Iu7bChQHsESqvGZ3FQRaI.jpg",
    "https://image.tmdb.org/t/p/w1920/577eXC8wFQT0eUrJcgznSiFPRmk.jpg",
    "https://image.tmdb.org/t/p/w1920/c6OLXfKAk5BKeR6broC8pYiCquX.jpg",
    "https://image.tmdb.org/t/p/w1920/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    "https://image.tmdb.org/t/p/w1920/y9ekzkPFmWSqUU3Kj0wHmYUM8qu.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/17821.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/25035.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/26885.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/21607.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/18965.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/26882.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/16891.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/24247.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/24252.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/22358.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/13479.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/7685.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/11174.jpg",
    "https://4kwallpapers.com/images/walls/thumbs_2t/26844.jpg",
    "https://image.tmdb.org/t/p/w1920/gddUsvfyySrM5k8B8wwJy2VRlBx.jpg",
    "https://image.tmdb.org/t/p/w1920/rbZvGN1A1QyZuoKzhCw8QPmf2q0.jpg",
    "https://image.tmdb.org/t/p/w1920/e3amyuWjfJ0HRPozbg6mKMlL2P6.jpg",
    "https://image.tmdb.org/t/p/w1920/iWak7wT0j6ycCc8lKr4NBz9c7n5.jpg",
];

export const cinematicAvatars = [
    {
        id: "scorsese-absolute-cinema",
        title: "Absolute Cinema",
        category: "Hollywood",
        url: "https://images.meme-arsenal.com/d65254f24e4d50b0b34f568884eb3c03.jpg",
    },
    {
        id: "tyler-durden",
        title: "Tyler Durden",
        category: "Hollywood",
        url: "https://i.pinimg.com/736x/d5/51/f7/d551f7af1e18e558bdbe5f1a1240d522.jpg",
    },
    {
        id: "blade-runner-k",
        title: "Officer K",
        category: "Hollywood",
        url: "https://i.pinimg.com/736x/4b/53/f1/4b53f15bc7eee568e3f627cfd4009b18.jpg",
    },
    {
        id: "anton-chigurh",
        title: "Anton Chigurh",
        category: "Hollywood",
        url: "https://i.ytimg.com/vi/opbi7d42s8E/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAbd0EsvyiVzdGvKX4s6aIHfWsbog",
    },

    {
        id: "pankaj-wasseypur",
        title: "The Wasseypur Stare",
        category: "Bollywood",
        url: "https://www.pinkvilla.com/images/2024-07/1065988642_gow.jpg",
    },
    {
        id: "srk-ddlj",
        title: "Raj",
        category: "Bollywood",
        url: "https://www.woggles.in/api/catalog/Blog%20Images/raj-in-dilwale-dulhania-le-jayenge.jpg",
    },
    {
        id: "akshay-welcome",
        title: "akshay",
        category: "Bollywood",
        url: "https://indianmemetemplates.com/wp-content/uploads/akshay-kumar-funny-expression.jpg",
    },
    {
        id: "irrfan-lunchbox",
        title: "Saajan",
        category: "Bollywood",
        url: "https://static.sociofyme.com/photo/113502790/113502790.jpg",
    }
];

export const genres = [
    { title: "Action" },
    { title: "Comedy" },
    { title: "Drama" },
    { title: "Horror" },
    { title: "Sci-Fi" },
    { title: "Romance" },
    { title: "Thriller" },
    { title: "Fantasy" }
];